title: "Kidnapped App"
description: "App allows discrete texts to be sent from the phone when a passphrase is spoken into the device's microphone"
author:
  name: "Isaac Dominguez"
  

theme: jekyll-theme-hacker
